// Mocks generated by Mockito 5.4.6 from annotations
// in my_health/test/unit/health_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:my_health/domain/entities/health_data.dart' as _i4;
import 'package:my_health/domain/repositories/health_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [HealthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHealthRepository extends _i1.Mock implements _i2.HealthRepository {
  MockHealthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.StepsRaw>> get stepsStream =>
      (super.noSuchMethod(
            Invocation.getter(#stepsStream),
            returnValue: _i3.Stream<List<_i4.StepsRaw>>.empty(),
          )
          as _i3.Stream<List<_i4.StepsRaw>>);

  @override
  _i3.Stream<List<_i4.HrRaw>> get heartRateStream =>
      (super.noSuchMethod(
            Invocation.getter(#heartRateStream),
            returnValue: _i3.Stream<List<_i4.HrRaw>>.empty(),
          )
          as _i3.Stream<List<_i4.HrRaw>>);

  @override
  bool get isSimulationMode =>
      (super.noSuchMethod(
            Invocation.getter(#isSimulationMode),
            returnValue: false,
          )
          as bool);

  @override
  _i3.Future<bool> checkPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#checkPermissions, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> requestPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermissions, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<_i4.StepsRaw>> getSteps(DateTime? start, DateTime? end) =>
      (super.noSuchMethod(
            Invocation.method(#getSteps, [start, end]),
            returnValue: _i3.Future<List<_i4.StepsRaw>>.value(<_i4.StepsRaw>[]),
          )
          as _i3.Future<List<_i4.StepsRaw>>);

  @override
  _i3.Future<List<_i4.HrRaw>> getHeartRate(DateTime? start, DateTime? end) =>
      (super.noSuchMethod(
            Invocation.method(#getHeartRate, [start, end]),
            returnValue: _i3.Future<List<_i4.HrRaw>>.value(<_i4.HrRaw>[]),
          )
          as _i3.Future<List<_i4.HrRaw>>);

  @override
  void startListening(Duration? pollInterval) => super.noSuchMethod(
    Invocation.method(#startListening, [pollInterval]),
    returnValueForMissingStub: null,
  );

  @override
  void stopListening() => super.noSuchMethod(
    Invocation.method(#stopListening, []),
    returnValueForMissingStub: null,
  );

  @override
  void setSimulationMode(bool? enabled) => super.noSuchMethod(
    Invocation.method(#setSimulationMode, [enabled]),
    returnValueForMissingStub: null,
  );
}
